3D Changes Perspectives:: Episode/Mini-Series: sub-text


URL: rtmp://live.restream.io/live

key: 


CHAT TOKEN: 


META DATA: template


###### \#seasonNUM \#SHOW


!!!!!!!!!!!!!!!!!   NOTHING  at ending song     !!!!!!!!!!!!!!!!!



    "I'm the intro!"




------------------ >>> THANK NETWORK PARTNERSHIPS <<<< -------------------- [#0000F8]
    

       >>> "OKAY   I wanna Thank !partnership! Find them on xTwitter among other social media platforms." <<<  [#00AAAA]

######	 Specific_partnership  ....>> .. <<


       >>> "I ALSO wanna Thank !specific Partnership! Find them on xTwitter among other social media platforms including some of the places you may watching this right here." <<< [#00AEEA]



     ------------------ >>> THANK SPONSOR<<< --------------------

       >>> "!segment/sponsor!" <<< 




  >> "  Okay, ! now let's roll in with the roll ins ! " << [#C112A4]




    >>>> PLAY SHOW INTRO <<<< [#C112A4]

--------------------------------------------




######	 CHECK AUDIO IF POSSIBLE <<<<<< [#AF0000]




######	 .. <<<<<<


>>!!
      "Welcome      into     the    Photon      of    the    Greater         4th    Demension           Quantum   Machine!"
                !!  !! !!<<




- https://www.youtube.com/@DeOrganized

    "I just want to point out this is DeOrangized Media. They a ton of content and videos on Stacks and Bitcoin among other token topics!"

  >>>>> show how the QR system works <<<<<




- https://beyondtheblockmedia.com/

    "I just want to point out this is how you can find beyond the block to discover more of what they have to offer!"

  >>>>> scroll around website <<<<<




- https://presearch.com/search?q=best%20coding%20ai


   "Today's free presearch querry is "best coding ai". Like always, I did not use this querry in today's episode research but that doesn't mean we won't have some overlapping links. If anything about today's episode interests you this free presearch query should help you find more to help you. Just replay after the show and scan the QR on your screen with your phone or QR reader to get this querry link to jump start your next rabbit hole!"



######	 BLANK PAGE => CATCH UP DEETS <<<<<<



>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>EXIT TO BACKGROUND<<<<<<<<<<<<<<<<<<<<<<<<<<<<
     

 >>>CATCH UP DEETS<<<


    "Background lore, history & quick info."   



>>>>>>>>>>>>>RETURN TO SHOW<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<








######	 ! You GOT This ! <<<<<<






- https://source.link


     "Talk about it"

          >>> DO SOMETHING THERE <<<

       "Explain the perspective and/or how it matters"







- https://source.link


     "Talk about it"

          >>> DO SOMETHING THERE <<<

       "Explain the perspective and/or how it matters"






- https://source.link


     "Talk about it"

          >>> DO SOMETHING THERE <<<

       "Explain the perspective and/or how it matters"






- https://source.link


     "Talk about it"

          >>> DO SOMETHING THERE <<<

       "Explain the perspective and/or how it matters"








>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>EXIT TO BACKGROUND<<<<<<<<<<<<<<<<<<<<<<<<<<<<



     >>>ENDING REMARK<<<




   " Even in development, it's a contest. If you don't have the social skills, selling skills, coding skills, or general knowledge of standard terminaology humiliation will be your friend. So find people with these skills and collaborate on a proposal or change because lone-wolf porposals are not the best way forward."

   " Just remember, Lopp claimed things that in practice are not really true like sure anyone can sign up and send anything but it takes extra steps and more to go further. To be hoenst, at this point I do not know If I will send that other email with the correct SPHINCS+ manipulation or not. If you think I should or should, comment below and perhaps tell me why."



    " I will be taking a short break after today's episode, so until next time. Don't stick to a perspective, try on another's perspective and see what happens. "





          >>>>PLAY OUTTRO VIDEO<<<<<





>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DURING EXIT MUSIC <<<<<<<<<<<<<<<<<<<<<<<<<<<<






######         >> .. <<    





######         >> .. <<    





######         >> .. <<    





######         >> .. <<    





######         >> .. <<    





```storage

- https://source.link


     "Talk about it"

          >>> DO SOMETHING THERE <<<

       "Explain the perspective and/or how it matters"



================  ==================
----------------  ------------------



- https://source.link


     "Talk about it"

          >>> DO SOMETHING THERE <<<

       "Explain the perspective and/or how it matters"




================  ==================
----------------  ------------------



- https://source.link


     "Talk about it"

          >>> DO SOMETHING THERE <<<

       "Explain the perspective and/or how it matters"




================  ==================
----------------  ------------------



- https://source.link


     "Talk about it"

          >>> DO SOMETHING THERE <<<

       "Explain the perspective and/or how it matters"





================  ==================
----------------  ------------------




- https://source.link


     "Talk about it"

          >>> DO SOMETHING THERE <<<

       "Explain the perspective and/or how it matters"




================  ==================
----------------  ------------------




- https://source.link


     "Talk about it"

          >>> DO SOMETHING THERE <<<

       "Explain the perspective and/or how it matters"




================  ==================
----------------  ------------------



- https://source.link


     "Talk about it"

          >>> DO SOMETHING THERE <<<

       "Explain the perspective and/or how it matters"




================  ==================
----------------  ------------------



- https://source.link


     "Talk about it"

          >>> DO SOMETHING THERE <<<

       "Explain the perspective and/or how it matters"





================  ==================
----------------  ------------------




- https://source.link


     "Talk about it"

          >>> DO SOMETHING THERE <<<

       "Explain the perspective and/or how it matters"





================  ==================
----------------  ------------------



- https://source.link


     "Talk about it"

          >>> DO SOMETHING THERE <<<

       "Explain the perspective and/or how it matters"




================  ==================
----------------  ------------------



- https://source.link


     "Talk about it"

          >>> DO SOMETHING THERE <<<

       "Explain the perspective and/or how it matters"




================  ==================
----------------  ------------------



- https://source.link


     "Talk about it"

          >>> DO SOMETHING THERE <<<

       "Explain the perspective and/or how it matters"





================  ==================
----------------  ------------------




- https://source.link


     "Talk about it"

          >>> DO SOMETHING THERE <<<

       "Explain the perspective and/or how it matters"





================  ==================
----------------  ------------------



- https://source.link


     "Talk about it"

          >>> DO SOMETHING THERE <<<

       "Explain the perspective and/or how it matters"




================  ==================
----------------  ------------------



- https://source.link


     "Talk about it"

          >>> DO SOMETHING THERE <<<

       "Explain the perspective and/or how it matters"




================  ==================
----------------  ------------------



- https://source.link


     "Talk about it"

          >>> DO SOMETHING THERE <<<

       "Explain the perspective and/or how it matters"

```



######         >> .. <<    





######         >> .. <<    





######         >> .. <<    


















